name: CI/CD Pipeline - All Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_LIFETIME: ${{ secrets.JWT_LIFETIME }}
  PORT: ${{ secrets.PORT }}
  CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
  BACKEND_DOMAIN: ${{ secrets.BACKEND_DOMAIN }}
  VITE_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}
  VITE_CLOUDINARY_API_KEY: ${{ secrets.VITE_CLOUDINARY_API_KEY }}
  VITE_CLOUDINARY_UPLOAD_PRESET: ${{ secrets.VITE_CLOUDINARY_UPLOAD_PRESET }}
  VITE_BACKEND_DOMAIN: ${{ secrets.VITE_BACKEND_DOMAIN }}


jobs:
   # 1. Job for Unit Tests
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '25.5'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm run test:unit

  # 2. Job for Integration Tests  
  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '25.5'
          cache: 'npm'
      - name: Install root dependencies
        run: npm ci
      - name: Install backend dependencies
        run: npm ci
        working-directory: ./backend
      - name: Run Integration Tests
        run: npm run test:api

  # 3. Job for Playwright E2E Tests
  playwright-test:
    timeout-minutes: 60
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Create auth directory
        run: mkdir -p tests/ui/auth/.auth
      - name: Install root dependencies
        run: npm ci
      - name: Install backend dependencies
        run: npm ci
        working-directory: ./backend
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:unit
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

   # 4. Job for k6 Performance Tests
  k6-tests:
    needs: playwright-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '25.5'
          cache: 'npm'
      - name: Start backend
        uses: ./.github/actions/start-backend  
      - name: Start frontend
        uses: ./.github/actions/start-frontend
      # 1. Install k6 on the GitHub Actions runner machine, as there is something wrong if install from npm
      - name: Setup k6
        uses: grafana/setup-k6-action@v1
      - name: Run k6 load test
        run: npm run test:perf

